### ISSUE TITLE
您好 请问您的gif图的效果是怎么得到的呢？

### ISSUE THREAD

**Issue by clytze0216** [wangx1996/CenterPillarNet#4]
您好，我也想做一个这样的多帧连续可视化效果，能否请问您的gif图是如何得到的呢？非常感谢！

**Comment by wangx1996** [comment]
@clytze0216 把结果用图片显示出来，然后用opencv写成视频就可以了

**Comment by clytze0216** [comment]
> @clytze0216 把结果用图片显示出来，然后用opencv写成视频就可以了

非常感谢您的回复！！！但是我是个新手，我想请问此过程是否指的是test.py中的line221 231那一部分
能否分享一下您当时的代码以用于学习，真的非常感谢！！期待您的回复，再次谢谢！
（如果我想显示行人、二轮车这些种类，我应该如何做呢？抱歉打扰，期待回复~谢谢！）

**Comment by wangx1996** [comment]
@clytze0216 是的，就是那一段代码，具体可查询opencv相关函数即可
